### PR TITLE
Improve error message

### LINKED ISSUE #11: Improve error message
## Need

```gherkin
As a developer
I want clear error messages
So that I can quickly identify the problem.
```

## Deliverables

- [ ] the error message includes the screenshot name and/or selector

## Solution

`expected baseline and screenshot of 'my-awesome-widget' (#awesome-widget-selector) to be identical`

### PR DESCRIPTION
**Pull request by adela-istrate-hs**
Closes #11

### CODE REVIEW

**Comment by adela-istrate-hs** [comment]
@andrei-picus-hs @valentin-radulescu-hs Can you review?

**Comment by adela-istrate-hs** [comment]
@andrei-picus-hs  @valentin-radulescu-hs Can you review?

**Comment by andrei-picus-hs** [comment]
LGTM

**Comment by valentin-radulescu-hs** [comment]
LGTM

**Pull request merged**
